### ISSUE TITLE
feat: GitHub CI

### ISSUE THREAD

**Issue by krishdevdb** [Skyhero-admin/Sky8-emu.js#4]
Create a github action in `.github/workflows` directory and name of `lint.yml`, with the following code
```yml
name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx eslint . --ext .js
 ```
